blog/urls.py
from django.conf.urls import url
from blog.views import *


urlpatterns = [
    #Example: /
    url(r'^$', PostLV.as_view(), name= 'index'),

    #Example: /post/ (Same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    #Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    #Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    #Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    #Example: /2012/nov/10
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name= 'post_day_archive'),

    #Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    #Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud' ),

    #Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name = 'tagged_object_list'),

    #Example: /search/
    url(r'^search/$', SearchFormView.as_view(), name= 'search'),

    #Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name = "add",
    ),

    #Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name = "change",
    ),

    #Example: /99/update
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name = "update",
    ),

    #Example: /99/delete
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name = "delete",
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name = 'home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    #url(r'^bookmark/$', BookmarkLV.as_view(), name = 'index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name = 'detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [
    url(r'^$', AlbumLV.as_view(), name= 'index'),

    url(r'^album/$', AlbumLV.as_view(), name= 'album_list'),

    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name= 'album_detail'),

    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name= 'photo_detail'),

    #Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(),
        name = "album_add",
    ),

    #Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(),
        name = "album_change",
    ),

    #Example: /album/99/update
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(),
        name = "album_update",
    ),

    #Example: /album/99/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(),
        name = "album_delete",
    ),

    #Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(),
        name = "photo_add",
    ),

    #Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(),
        name = "photo_change",
    ),

    #Example: /photo/99/update
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(),
        name = "photo_update",
    ),

    #Example: /photo/99/delete
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(),
        name = "photo_delete",
    ),
]

photo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from photo.fields import ThumbnailImageField
from django.contrib.auth.models import User

class Album(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField('One Line Description', max_length=100, blank = True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank = True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add = True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo, fields = ['image', 'title', 'description'], extra = 2)

photo/views.py
#from django.shortcuts import render
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin


class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

#photo ---
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

#album --
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')


#-- inline form set
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html' #can be commented out. _form suffix is default template of CreateView

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES) #request.FILES for file uploading
        else:
            context['formset'] = PhotoInlineFormSet() #Get request
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save() #save album
            formset.instance = self.object #ForeignKey를 방금 save한 앨범으로 세팅하는 듯...
            formset.save() #save photos
            return redirect(self.object.get_absolute_url()) #album 상세 페이지로 이동
        else:
            return self.render_to_response(self.get_context_data(form=form)) #유효하지 않은면 다시 출력

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset'] #photo
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save() #save record to table
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends "base.html" %}
{% block title %}album_change_list.html{% endblock %}
{% block content %}
<h3>Album Change - {{user}}</h3>
<table class="change-list">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Owner</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  {% for item in object_list %}
  <tr>
    <td>{{ item.name }}</td>
    <td>{{ item.description }}</td>
    <td>{{ item.owner }}</td>
    <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
    <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}
{% block title %}album_confirm_delete.html{% endblock %}
{% block content %}
<h3>Album Delete</h3>
<form action="." method="post">{% csrf_token %}
  <p>Are you sure to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}
{% block title %}album_detail.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock%}
{% block content %}
<h3 style="display|inline">{{ object.name }}</h3>
&emsp;<b><i>{{ object.description }}</i></b>
<hr/>
<div class="album-detail">
  {% for photo in object.photo_set.all %}
    <div class="album-detail-photo">
      <a href="{{ photo.get_absolute_url }}">
        <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
      </a>
      <li>{{ photo.title }}</li>
      <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
    </div>
  {% endfor %}
</div>
{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}
{% block title %}album_form.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}
{% block content %}
<h3>Album-Photo InlineFormSet</h3>
{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" method="post" action=".">
{% else %}
<form action="." method="post">
{% endif %}
{% csrf_token %}
{% if form.errors %}
<p class="errornote">Wrong! Please correct the FORM error(s) below.</p>
<p class="errornote">{{ form.errors }}</p>
{% endif %}
{% if formset.errors %}
<p class="errornote">Wrong! Please correct the FORMSET error(s) below.</p>
<p class="errornote">{{ formset.errors }}</p>
{% endif %}
<h4>Create or Update Album contents.</h4>
<fieldset class="algined">
  <div class="form-row">
    {{ form.name.label_tag }} {{ form.name }}
  </div>
  <div class="form-row">
    {{ form.description.label_tag }} {{ form.description }}
  </div>
</fieldset>
<h4>Create or Update Photo contents.</h4>
{{ formset.management_form }} {# formset data를 다룰 때 반드시 호출, django template engine에 form number 등 전달  #}
{% for form in formset %}
  {{ form.id }}
  <fieldset class="aligned">
    <div class="form-row">
      {{ form.image.label_tag }} {{ form.image }}
    </div>
    <div class="form-row">
      {{ form.title.label_tag }} {{ form.title }}
    </div>
    <div class="form-row">
      {{ form.description.label_tag }} {{ form.description }}
    </div>
  </fieldset>
{% endfor %}
<div class="submit-row">
  <input type="submit" value="Submit"/>
</div>
<script type="text/javascript">
  document.getElementById('id_name').focus();
</script>
</form>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}
{% block title %}album_list.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
{% block content %}
{% for item in object_list %}
<div class="clear_float">
  <h3 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h3>
  &emsp;<b><i>{{ item.description }}</i></b>
</div>
<hr/>
<div class="album_list">
  {% for photo in item.phto_set.all|slice:":5" %}
  <div class="album-list-photo">
    <a href="{{ photo.get_absolute_url }}">
      <img class = "thumbnail" src = "{{ photo.image.thumb_url }}" />
    </a>
  </div>
  {% endfor %}
</div>
{% endfor %}
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}
{% block title %}photo_change_list.html{% endblock %}
{% block content %}
<h3>Photo Change - {{user}}</h3>
<table class="change-list">
  <tr>
    <th>Album</th>
    <th>Title</th>
    <th>Description</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  {% for item in object_list %}
  <tr>
    <td>{{ item.album }}</td>
    <td>{{ item.title }}</td>
    <td>{{ item.description }}</td>
    <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
    <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}
{% block title %}photo_confirm_delete.html{% endblock %}
{% block content %}
<h3>Photo Delete</h3>
<form action="." method="post">{% csrf_token %}
  <p>Are you sure to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}
{% block title %}photo_detail.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
{% block content %}
<h3>{{ object.title }}</h3>
<table class="photo-detail">
  <tr>
    <td>
      <a href="{{ object.image.url }}">
        <img style="max-width:100%" src="{{ object.image.url }}" />
      </a>
    </td>
    <td>
      <ul>
        <li>Photo Description</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>(blank)</p>
        {% endif %}
        <li>Album Name</li>
        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
      </ul>
    </td>
  </tr>
</table>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}
{% block title %}photo_form.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}
{% block content %}
<h3>Photo Create/Update - {{user}}</h3>
{% if form.is_multipart %}
<form enctype="multipart/form-data" method="post" action=".">
{% else %}
<form action="." method="post">
{% endif %}
{% csrf_token %}
{% if form.errors %}
<p class="errornote">Wrong! Please correct the FORM error(s) below.</p>
<p class="errornote">{{ form.errors }}</p>
{% endif %}
<h4>This is a creation or update form for your photo.</h4>
<fieldset class="algined">
  <div class="form-row">
    {{ form.image.label_tag }} {{ form.image }}
  </div>
  <div class="form-row">
    {{ form.album.label_tag }} {{ form.album }}
    <button type="button"><a href="{% url "photo:album_add" %}">Add Album</a></button>
  </div>
  <div class="form-row">
    {{ form.title.label_tag }} {{ form.title }}
  </div>
  <div class="form-row">
    {{ form.description.label_tag }} {{ form.description }}
  </div>
</fieldset>

<div class="submit-row">
  <input type="submit" value="Submit"/>
</div>
<script type="text/javascript">
  document.getElementById('id_album').focus();
</script>
</form>
{% endblock %}