blog/urls.py
from django.conf.urls import url
from blog.views import *


urlpatterns = [
    #Example: /
    url(r'^$', PostLV.as_view(), name= 'index'),

    #Example: /post/ (Same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    #Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    #Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    #Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    #Example: /2012/nov/10
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name= 'post_day_archive'),

    #Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    #Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud' ),

    #Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name = 'tagged_object_list'),

    #Example: /search/
    url(r'^search/$', SearchFormView.as_view(), name= 'search'),

    #Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name = "add",
    ),

    #Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name = "change",
    ),

    #Example: /99/update
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name = "update",
    ),

    #Example: /99/delete
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name = "delete",
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name = 'home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    #url(r'^bookmark/$', BookmarkLV.as_view(), name = 'index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name = 'detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [
    url(r'^$', AlbumLV.as_view(), name= 'index'),

    url(r'^album/$', AlbumLV.as_view(), name= 'album_list'),

    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name= 'album_detail'),

    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name= 'photo_detail'),

    #Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(),
        name = "album_add",
    ),

    #Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(),
        name = "album_change",
    ),

    #Example: /album/99/update
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(),
        name = "album_update",
    ),

    #Example: /album/99/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(),
        name = "album_delete",
    ),

    #Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(),
        name = "photo_add",
    ),

    #Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(),
        name = "photo_change",
    ),

    #Example: /photo/99/update
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(),
        name = "photo_update",
    ),

    #Example: /photo/99/delete
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(),
        name = "photo_delete",
    ),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
       {% block title %}Tyler Site{% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
</head>
<body>
<div id="header">
  <h4 class='maintitle'><strong><a class="nav-link" href="{% url 'home' %}">Home</a></strong></h4>
  {% if user.is_active %}
  <h4 class="welcome">Welcome,
    <strong>{% firstof user.get_short_name user.get_username %}</strong>
    <a href="{% url 'logout' %}">Logout</a>
  </h4>
  {% else %}
  <h4 class="welcome">Welcome, Anonymous
     <a href="{% url 'login' %}">Login</a>
  </h4>
  {% endif %}
</div>
<div id="menu">
  <ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link" href="{% url 'blog:index' %}">Blog</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'photo:index' %}">Photo</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'blog:search' %}">Search</a></li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Add</a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
        <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
        {% if user.is_active %}
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
      </div>
    </li>
  </ul>
</div>
<div class="container" id="content">
  {% block content %}{% endblock %}
</div>
{% block footer %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}home.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}
{% block content %}
<h3><i><strong>Time goes on</strong></i></h3>
{% endblock content %}
{% block footer %}
<div id="footer">
    &copy; tyler 2017
</div>
{% endblock footer %}